### ISSUE TITLE
Paid Module

### ISSUE THREAD

**Issue by karthikTVS** [hansemannn/titanium-play-billing-demo#1]
Is the new version of Play billing module is a paid one?

**Comment by hansemannn** [comment]
Hi there! I rebuilt the iOS/Android modules from the scratch and added parity for them, since that was also not possible so far. Also, Android now uses the "Play Billing" library instead of the (deprecated) AIDL files. If that version is of interest for you, feel free to reach out via TiSlack (tislack.org), you find me via `@hans`.
